using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using TMPro;
using UnityEngine.SceneManagement;

public class ResultPopup : MonoBehaviour
{
    public TextMeshProUGUI titleLabel;
    public TextMeshProUGUI scoreLabel;
    public GameObject highScorePopup;

    private void OnEnable()
    {
        Time.timeScale = 0;

        if (GameManager.Instance.isCleared)
        {
            SaveHighScore();

            titleLabel.text = "Cleared!";
            scoreLabel.text = GameManager.Instance.timeLimit.ToString("#.##");
        }
        else
        {
            titleLabel.text = "Game Over..";
            scoreLabel.text = "";
        }
    }

    void SaveHighScore()
    {
        float score = GameManager.Instance.timeLimit;
        string currentScoreString = score.ToString("#.###");

        string savedScoreString = PlayerPrefs.GetString("HighScores", "");

        if (savedScoreString=="")
        {
            PlayerPrefs.SetString("HighScores", currentScoreString);
        }
        else
        {
            string[] scoreArray = savedScoreString.Split(",");
            List<string> scoreList = new List<string>(scoreArray);

            for (int i=0;i<scoreList.Count;i++)
            {
                float savedScore = float.Parse(scoreList[i]);
                if (savedScore<score)
                {
                    scoreList.Insert(i, currentScoreString);
                    break;
                }
            }

            if (scoreArray.Length == scoreList.Count)
            {
                scoreList.Add(currentScoreString);
            }

            if (scoreList.Count>10)
            {
                scoreList.RemoveAt(10);
            }

            string result = string.Join(",", scoreList);
            PlayerPrefs.SetString("HighScores", result);

        }

        PlayerPrefs.Save();

    }

    public void PlayAgainPressed()
    {
        Time.timeScale = 1;
        SceneManager.LoadScene("GameScene");
    }

    public void HighScorePressed()
    {
        highScorePopup.SetActive(true);
    }
}
